#!/usr/bin/env bash
# How to install nginx on a remote server and configure it
sudo apt-get update -y 
sudo apt-get install -y nginx
sudo sed -i 's/listen 80 default_server;/listen 80;/' /etc/nginx/sites-available/default
sudo bash -c 'echo "Holberton School for the win!" > /var/www/html/index.html'
sudo nginx -s reload
